### ISSUE TITLE
Release as a gem?

### ISSUE THREAD

**Issue by joshbeckman** [reiterate-app/mastodon-social#1]
Looks like this was intended for public release as a gem, any interest in taking it over the finish line?

**Comment by reiterate-app** [comment]
I didn’t expect anyone would be interested in it, and mainly packaged it to make it convenient for myself. I don’t have a lot of experience packaging code nicely for public consumption. What would I need to do to “take it over the finish line” as you say? Would you be willing to help?

**Comment by joshbeckman** [comment]
Sure! Largely, it looks like all that's left to do is `gem publish`: https://guides.rubygems.org/publishing/

**Comment by reiterate-app** [comment]
Okay! I updated the documentation and made an official release:
https://github.com/reiterate-app/mastodon-social/releases/tag/0.1.0

It's been pushed to rubygems.org.

Please let me know if this works for you! You would be the first person ever to use any open source code I've written.

**Comment by joshbeckman** [comment]
Congratulations on publishing a gem!

Live at https://rubygems.org/gems/mastodon-social

I'll be trying it out soon.
